### ISSUE TITLE
ValueError: Layer weight shape (3L, 3L, 640L, 64L) not compatible with provided weight shape (64, 3, 3, 3)

### ISSUE THREAD

**Issue by xycim** [marcellacornia/mlnet#7]
hi, 
   when i run your codes, it doesnot work with hint("ValueError: Layer weight shape (3L, 3L, 640L, 64L) not compatible with provided weight shape (64, 3, 3, 3)").  Any advices for me?

**Comment by sino1Ping** [comment]
same error occurs to me!    with    win7    anaconda 4.2    python 2.7  and  theano 0.9.0, any suggestion?

**Comment by baraldilorenzo** [comment]
Dear @xycim, @sino1Ping,

please see this issue: #2 and see if it works for you.

**Comment by sino1Ping** [comment]
hi @baraldilorenzo  
Thank you for your reminding.  Now the "image_data_format" and "backend" in json file configured properly. I modified "from keras import initializations" to "from keras import regularizers",due to the keras version 2.0.4
In win7 system, I run into new error : "Layer weight shape (3L, 3L, 3L, 64L) not compatible with provided weight shape (64, 3, 3, 3)"
And in ubuntu system, the hint is "Layer weight shape (3, 3, 3, 64) not compatible with provided weight shape (64, 3, 3, 3)"

And when I set firt layer weights to None , the error hint is"Layer weight shape (3L, 3L, 64L, 64L) not compatible with provided weight shape (64, 64, 3, 3)"

and first two layers weights to None : "Layer weight shape (3L, 3L, 64L, 128L) not compatible with provided weight shape (128, 64, 3, 3)"

same issue with #1.but I'm sure I configured properly, and added backend.set_image_data_format("channels_first")" in the beginning of program. the same error still occurs

ps: I'm using theano 0.9.0 keras 2.0.4 both in win7 and ubuntu system

**Comment by marcellacornia** [comment]
Hi @sino1Ping,
you have to use Keras 1.1.0. Unfortunately, this code is not compatible with Keras 2.

**Comment by sino1Ping** [comment]
Thanks! It works.

**Comment by kmamine** [comment]
> 
> 
> Thanks! It works.

What did you do ?
